name: CI

on:
  push:
    branches:
     - master
    tags:
      - '*'
  pull_request:
    branches:
     - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - mariadb
          - mysql

    defaults:
      run:
        working-directory: ./test

    env:
      BUILD_IMAGE_TAG: ${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Build & Start
        run: docker compose up --detach --wait ${{ matrix.service }}

      - name: Dump & Diff
        run: >
          docker compose exec ${{ matrix.service }}
          mysqldump --compact --skip-extended-insert db
          |
          diff --unified --color --ignore-trailing-space expected/${{ matrix.service }}.sql -

      - name: Cleanup
        if: ${{ always() }}
        run: docker compose down --rmi=all --volumes